// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvJZD7jp7eyxvPLgXTMLhjjEBtWVxpO0A',
    appId: '1:867852799588:web:be9569ed89df31ccc65971',
    messagingSenderId: '867852799588',
    projectId: 'fir-flutter-login-56739',
    authDomain: 'fir-flutter-login-56739.firebaseapp.com',
    storageBucket: 'fir-flutter-login-56739.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiM_xiFiaqCE-2jv2qweE2mNLMBWABHSo',
    appId: '1:867852799588:android:0da9e841c29b4188c65971',
    messagingSenderId: '867852799588',
    projectId: 'fir-flutter-login-56739',
    storageBucket: 'fir-flutter-login-56739.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz6CVmTKaxEO-yzJYnOjrP1v82MzaTDyw',
    appId: '1:867852799588:ios:f33b93fcd06486e3c65971',
    messagingSenderId: '867852799588',
    projectId: 'fir-flutter-login-56739',
    storageBucket: 'fir-flutter-login-56739.firebasestorage.app',
    iosClientId: '867852799588-0oas99gileabe9rr124fj1h555lgau2o.apps.googleusercontent.com',
    iosBundleId: 'com.gideon.demoGetxSupabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz6CVmTKaxEO-yzJYnOjrP1v82MzaTDyw',
    appId: '1:867852799588:ios:f33b93fcd06486e3c65971',
    messagingSenderId: '867852799588',
    projectId: 'fir-flutter-login-56739',
    storageBucket: 'fir-flutter-login-56739.firebasestorage.app',
    iosClientId: '867852799588-0oas99gileabe9rr124fj1h555lgau2o.apps.googleusercontent.com',
    iosBundleId: 'com.gideon.demoGetxSupabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvJZD7jp7eyxvPLgXTMLhjjEBtWVxpO0A',
    appId: '1:867852799588:web:39757572aa9c94e0c65971',
    messagingSenderId: '867852799588',
    projectId: 'fir-flutter-login-56739',
    authDomain: 'fir-flutter-login-56739.firebaseapp.com',
    storageBucket: 'fir-flutter-login-56739.firebasestorage.app',
  );
}
